#!/bin/bash

if [ "x$1" == "x--create" ] ; then
   appname=$2
   package=$3
   rootclass=$4
   icon=$5
   appdisplay=$6
   resourcename=$7
   rosappname=$8
   cat > AndroidManifest.xml << EOF
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
	package="$package" android:versionCode="1"
	android:versionName="1.0">
	<uses-sdk android:minSdkVersion="9" />

	<application android:icon="@drawable/$icon" android:label="@string/app_name">

		<activity android:name=".$appname" android:label="@string/app_name"
			android:screenOrientation="landscape" android:configChanges="orientation|keyboardHidden">
			<intent-filter>
				<action android:name="android.intent.action.MAIN" />
				<category android:name="android.intent.category.LAUNCHER" />
			</intent-filter>
			<intent-filter>
				<action android:name="$package.$rootclass" />
				<category android:name="android.intent.category.DEFAULT" />
			</intent-filter>
		</activity>
		<activity android:name="ros.android.activity.MasterChooserActivity"
			android:label="@string/app_name">
		</activity>
	</application>

	<uses-permission android:name="android.permission.INTERNET"></uses-permission>
  <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
  <uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/>
  <uses-permission android:name="android.permission.CHANGE_WIFI_STATE"/>
</manifest>
EOF
   cat > manifest.xml << EOF
<package>
  <description brief="$appdisplay">
  	       TODO
  </description>
  <author>TODO</author>
  <license>BSD</license>
  <review status="unreviewed" notes=""/>
  <url>http://ros.org/wiki/ TODO</url>
  <depend package="appmanandroid"/>

  <export>
    <rosjava-android-app />
  </export>
</package>
EOF
   cat > Makefile << EOF
include \$(shell rospack find rosjava_bootstrap)/rosjava.mk
EOF
   cat > build.xml << EOF
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<project basedir="." default="compile" name="$appname">
  
  <property file="ros.properties"/>
  <import file="\${ros.pkg.appmanandroid.dir}/build_app.xml" />
</project>
EOF

   mkdir -p res/values
   mkdir -p res/drawable
   mkdir -p res/layout
   mkdir -p res/menu
   mkdir -p src

   cat > res/values/strings.xml << EOF
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <string name="app_name">$appdisplay</string>
</resources>
EOF
   cat > res/layout/main.xml <<EOF
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
              android:orientation="horizontal"
              android:layout_width="fill_parent"
              android:layout_height="fill_parent"
              android:id="@+id/main_layout">
  <LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
                android:orientation="vertical"
                android:layout_width="fill_parent"
                android:layout_height="fill_parent"
                android:id="@+id/main_layout">
    <LinearLayout android:orientation="horizontal" android:layout_width="fill_parent" android:layout_height="wrap_content"
                  android:gravity="right"
                  android:background="#ff404040"
                  android:id="@+id/top_bar" />
    <!--Add your layout here -->
  </LinearLayout>
</LinearLayout>
EOF

   cat > res/menu/${resourcename}_menu.xml <<EOF
<?xml version="1.0" encoding="utf-8"?>
<menu xmlns:android="http://schemas.android.com/apk/res/android">
  <item android:title="Kill" android:id="@+id/kill"></item>
</menu>
EOF


   dir=src/`echo $package | sed s/\\\\./\\\\//g`
   mkdir -p $dir
   cat > $dir/${rootclass}.java <<EOF
/*
 * Copyright (C) 2011 Google Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
package $package;

import ros.android.activity.RosAppActivity;
import android.os.Bundle;
import org.ros.node.Node;
import android.util.Log;
import android.widget.Toast;
import android.view.Menu;
import android.view.MenuInflater;
import android.view.MenuItem;

//TODO: search for all instances of TODO

/**
 * @author damonkohler@google.com (Damon Kohler)
 * @author pratkanis@willowgarage.com (Tony Pratkanis)
 */
public class $rootclass extends RosAppActivity {
  /** Called when the activity is first created. */
  @Override
  public void onCreate(Bundle savedInstanceState) {
    setDefaultAppName("$rosappname");
    setDashboardResource(R.id.top_bar);
    setMainWindowResource(R.layout.main);
    super.onCreate(savedInstanceState);
    
    //TODO: add code
    //Called on creation. ROS hasn't started yet, so don't start
    //anything that depends on ROS. Instead, look up things like
    //resources. Initialize your layout here.
  }
  
  /** Called when the node is created */
  @Override
  protected void onNodeCreate(Node node) {
    super.onNodeCreate(node);
    //TODO: Put your initialization code here
  }

  /** Called when the node is destroyed */
  @Override
  protected void onNodeDestroy(Node node) {
    super.onNodeDestroy(node);
    //TODO: Put your shutdown code here for things the reference the node
  }
  
  /** Creates the menu for the options */
  @Override
  public boolean onCreateOptionsMenu(Menu menu) {
    MenuInflater inflater = getMenuInflater();
    inflater.inflate(R.menu.${resourcename}_menu, menu);
    return true;
  }

  /** Run when the menu is clicked. */
  @Override
  public boolean onOptionsItemSelected(MenuItem item) {
    switch (item.getItemId()) {
    case R.id.kill: //Shutdown if the user clicks kill
      android.os.Process.killProcess(android.os.Process.myPid());
      return true;
    //TODO: add cases for any additional menu items here.
    default:
      return super.onOptionsItemSelected(item);
    }
  }
}
EOF
else
   echo "Usage: $0 --create <appname> <package> <rootclass> <icon>"
   echo "                   <display-name> <resource-name> <rosappname>:"
   echo "              creates all the files for a ros android app"
   echo "              WARNING: will overwrite existing files!"
   echo "              Run this inside of a pre-existing directory inside"
   echo "              your ROS package path."
   echo "Example: $0 --create PanTilt ros.android.pantilt PanTilt pantilt \"Pan and Tilt Viewer\" pan_tilt \"pr2_pan_tilt/pr2_pan_tilt\""
fi


