# Wrapper Makefile to call "ant" in the correct way.

debug:
	ant -f build-wrapper.xml debug

clean:
	ant -f build-wrapper.xml clean

install:
	ant -f build-wrapper.xml install

compile:
	ant -f build-wrapper.xml compile
